networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
      - db_online
      - db_users
    networks:
      - dev

  backend:
    build:
      context: ./design_smart_home
      dockerfile: Dockerfile
    networks:
      - dev

  db_online:
    build:
      context: ./DSH_db_online
      dockerfile: Dockerfile
    networks:
      - dev
    depends_on:
      - db_devices

  db_users:
    build:
      context: ./DSH_db_users
      dockerfile: Dockerfile
    networks:
      - dev
    depends_on:
      - db_usrs

  db_usrs:
    container_name: "dsh_db_users"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dsh_db_users
    ports:
      - "5433:5432"
    networks:
      - dev

  db_devices:
    container_name: "dsh_db_devices"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dsh_db_devices
    ports:
      - "5432:5432"
    networks:
      - dev

  frontend:
    build:
      context: ./design_smart_home_frontend
    networks:
      - dev