"""add userid

Revision ID: 8cdd35d40ada
Revises: bbe24d1570e1
Create Date: 2025-04-29 23:29:16.863513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cdd35d40ada'
down_revision: Union[str, None] = 'bbe24d1570e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('user_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'user_id')
    # ### end Alembic commands ###
