"""repolace model device

Revision ID: bbe24d1570e1
Revises: e2564cad8ba4
Create Date: 2025-02-10 13:50:43.379372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe24d1570e1'
down_revision: Union[str, None] = 'e2564cad8ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('data_type', sa.String(length=10), nullable=False))
    op.drop_column('devices', 'type_value')
    op.drop_column('devices', 'type_device')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('type_device', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.add_column('devices', sa.Column('type_value', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_column('devices', 'data_type')
    # ### end Alembic commands ###
